name             'chef-cloudfuse'
maintainer       'PE, pf.'
maintainer_email 'peychart@mail.pf'
license          'GNU Public License 3.0'
description      'Installs/Configures chef-cloudfuse'
long_description 'Installs/Configures chef-cloudfuse'
version          '0.1.0'
